//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int SID { get; set; }
        public string SName { get; set; }
        public string SBirthDate { get; set; }
        public string SUserName { get; set; }
        public string SPassword { get; set; }
        public string SGPA { get; set; }
    }
}
