//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccressProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInfoTable
    {
        public int CID { get; set; }
        public string CName { get; set; }
        public Nullable<int> CCcedit { get; set; }
        public Nullable<int> CCID { get; set; }
    
        public virtual CourseTokenByStudentTable CourseTokenByStudentTable { get; set; }
    }
}
